#site settings
title: Illuminati Solutions
email: asankahendahewa@gmail.com
description: We illuminate your world



# Build settings

markdown: kramdown
permalink: pretty


port: 8070



sass:
  sass_dir: assets/css
  style: :nested