#-------------------------------
# About Section

    #links

link-fb: https://www.facebook.com/asankahendahewa
link-twtr: https://twitter.com/AsankaHH
link-gp: https://plus.google.com/+AsankaHendahewa
link-linkdin: https://lk.linkedin.com/in/asankahendahewa

# NOTE: The avatar is defined in the all.sass document.

skills:
- {name: Communication, value: '9'}
- {name: Organizing, value: '7'}
- {name: Learning, value: '10'}
- {name: Leadership, value: '9'}
- {name: Programming, value: '7'}
- {name: Photography, value: '8'}
- {name: UX Design, value: '5'}
- {name: Team Work, value: '6'}


#-------------------------------
# Work Section

projects:
- {name: sunsets, folder: 'proj-01'}
- {name: Flowers, folder: 'proj-02'}
- {name: Landscapes, folder: 'proj-03'}
- {name: Fire Works, folder: 'proj-04'}
- {name: Black and white, folder: 'proj-05'}
- {name: The Eyes, folder: 'proj-06'}
- {name: insects, folder: 'proj-07'}
- {name: HDR, folder: 'proj-08'}



#-------------------------------
# Client Section

#clients:
#- {avatar: face-jackiesaik.jpg, name: 'Pavani Lakshika', title: 'Assistant Marketing Manager,Godrej', quote: '<strong>Lorem ipsum dolor sit amet, </strong>consectetur adipiscing elit. Vestibulum non tortor et turpis mattis porta. In hac habitasse platea dictumst. Duis sit amet ex eget massa hendrerit sodales ut quis ante. Donec tincidunt venenatis fermentum. Vestibulum non justo in augue vehicula posuere non quis lorem. Nulla eget mattis mauris. Ut. ',logo: 'logo1.png'}
#- {avatar: face-aaroni.jpg, name: 'Aaroni', title: 'Someone', quote: '<strong>hey</strong>consectetur adipiscing elit. Vestibulum non tortor et turpis mattis porta. In hac habitasse platea dictumst. Duis sit amet ex eget massa hendrerit sodales ut quis ante. Donec tincidunt venenatis fermentum. Vestibulum non justo in augue vehicula posuere non quis lorem. Nulla eget mattis mauris. Ut. ', logo: 'logo2.png'}
#- {avatar: face-atariboy.jpg, name: 'Beard Man', title: 'President, Bearders', quote: '<strong>Good, </strong>consectetur adipiscing elit. Vestibulum non tortor et turpis mattis porta. In hac habitasse platea dictumst. Duis sit amet ex eget massa hendrerit sodales ut quis ante. Donec tincidunt venenatis fermentum. Vestibulum non justo in augue vehicula posuere non quis lorem. Nulla eget mattis mauris. Ut. ', logo: 'logo3.png' }
#- {avatar: face-teleject.jpg, name: 'One th last', title: 'I dont know', quote: '<strong>Boo yeah </strong>consectetur adipiscing elit. Vestibulum non tortor et turpis mattis porta. In hac habitasse platea dictumst. Duis sit amet ex eget massa hendrerit sodales ut quis ante. Donec tincidunt venenatis fermentum. Vestibulum non justo in augue vehicula posuere non quis lorem. Nulla eget mattis mauris. Ut. ', logo: 'logo4.png'}

clients:
- {avatar: dp-anush.jpg, name: 'Anushan Sivanndan', title: 'Developer/Social Interactor', quote: '<strong>Lorem ipsum dolor sit amet, </strong>consectetur adipiscing elit. Vestibulum non tortor et turpis mattis porta. In hac habitasse platea dictumst. Duis sit amet ex eget massa hendrerit sodales ut quis ante. Donec tincidunt venenatis fermentum. Vestibulum non justo in augue vehicula posuere non quis lorem. Nulla eget mattis mauris. Ut. ',logo: 'logo-code.png'}
- {avatar: dp-asa.jpg, name: 'Asanka Hendahewa', title: 'Developer', quote: '<strong>There are no hard or easy work. it is just how much you willing to commit for done the work</strong> <br>Asanka is Computer security undergraduate of NSBM with Plymouth University since 2014. he is flexible person who like to learn new things and has ability to adopt in to new environment in no time.he is doing photography in his free time for relaxing and can view his photos on <a href="https://www.facebook.com/AHHIllusions/">Illusions</a>. Skilled developer in C#,Java,PHP and web languages. in same time he is a UI/UX enthusiast.', logo: 'logo-idea.png'}
- {avatar: dp-bimal.jpg, name: 'Bimal Kaveesha', title: 'Developer/Writer', quote: '<strong>Good, </strong>consectetur adipiscing elit. Vestibulum non tortor et turpis mattis porta. In hac habitasse platea dictumst. Duis sit amet ex eget massa hendrerit sodales ut quis ante. Donec tincidunt venenatis fermentum. Vestibulum non justo in augue vehicula posuere non quis lorem. Nulla eget mattis mauris. Ut. ', logo: 'logo-social.png' }
- {avatar: dp-kosala.jpg, name: 'Kosala Surawimala', title: 'Designer', quote: '<strong>Boo yeah </strong>consectetur adipiscing elit. Vestibulum non tortor et turpis mattis porta. In hac habitasse platea dictumst. Duis sit amet ex eget massa hendrerit sodales ut quis ante. Donec tincidunt venenatis fermentum. Vestibulum non justo in augue vehicula posuere non quis lorem. Nulla eget mattis mauris. Ut. ', logo: 'logo-design.png'}
- {avatar: dp-mashoor.jpg, name: 'Ahamed Mashoor', title: 'Database Engineer', quote: '<strong>Boo yeah </strong>consectetur adipiscing elit. Vestibulum non tortor et turpis mattis porta. In hac habitasse platea dictumst. Duis sit amet ex eget massa hendrerit sodales ut quis ante. Donec tincidunt venenatis fermentum. Vestibulum non justo in augue vehicula posuere non quis lorem. Nulla eget mattis mauris. Ut. ', logo: 'logo-db.png'}


